- src/Services/EnvironmentService.php
- src/Services/HttpService.php
- src/Unzer.php
- test/unit/Services/HttpServiceTest.php
- test/unit/Services/ResourceServiceTest.php
- rename to PAPI
- replace api url in src and test
> [change] (UMCS-247)

- examples/Alipay/index.php
- examples/Bancontact/index.php
- examples/BankTransfer/index.php
- examples/Card/index.php
- examples/CardRecurring/index.php
- examples/EPSCharge/index.php
- examples/EmbeddedPayPage/index.php
- examples/Giropay/index.php
- examples/HirePurchaseDirectDebit/confirm.php
- examples/HirePurchaseDirectDebit/index.php
- examples/HostedPayPage/index.php
- examples/IDeal/index.php
- examples/Invoice/index.php
- examples/InvoiceFactoring/index.php
- examples/InvoiceGuaranteed/index.php
- examples/PayPal/index.php
- examples/PayPalRecurring/index.php
- examples/Prepayment/index.php
- examples/Przelewy24/index.php
- examples/SepaDirectDebitGuaranteed/index.php
- examples/Sofort/index.php
- examples/Webhooks/fetchAll.php
- examples/Webhooks/index.php
- examples/Webhooks/removeAll.php
- examples/Wechatpay/index.php
- examples/index.php
- update static files.
- correct integrity check for jquery.
> [change] (UMCS-20)

- CHANGELOG.md
- src/Resources/PaymentTypes/Card.php
- src/Unzer.php
- test/BasePaymentTest.php
- test/integration/PaymentTypes/CardTest.php
- test/unit/Resources/PaymentTypes/CardTest.php
- add email field to card type.
- update card tests.
> Umcs 44/change/add cards email

- examples/CardExtended/Constants.php
- set correct controller url for card extended example.
> [change] (UMCS-49)

- CHANGELOG.md
- src/Adapter/ApplepayAdapter.php
- src/Constants/ApplepayValidationDomains.php
- src/Constants/IdStrings.php
- src/Exceptions/ApplepayMerchantValidationException.php
- src/Resources/EmbeddedResources/ApplePayHeader.php
- src/Resources/ExternalResources/ApplepaySession.php
- src/Resources/PaymentTypes/Applepay.php
- src/Services/EnvironmentService.php
- src/Services/ResourceService.php
- src/Unzer.php
- test/integration/ApplepayAdapterTest.php
- test/integration/PaymentTypes/ApplepayTest.php
- test/unit/Adapter/ApplepaySessionTest.php
- test/unit/Resources/AbstractUnzerResourceTest.php
- test/unit/Resources/EmbeddedResources/ApplePayHeaderTest.php
- test/unit/Resources/PaymentTypes/ApplePayTest.php
- test/unit/Services/ResourceServiceTest.php
Transfere feature branch into develop
> Umcs 144/feature/applepay

- CHANGELOG.md
Simplify compare links in changelog
> [change] (UMCS-144) - changelog: simplify compare links

- CHANGELOG.md
- examples/Card/index.php
- examples/CardExtended/index.php
- examples/CardRecurring/index.php
- Ensure that error messages are displayed just one time.
> Umcs 120/change/card example form validation

- CHANGELOG.md
- examples/EmbeddedPayPage/Controller.php
- examples/HostedPayPage/Controller.php
Add missing customer information that are required for payment with Instalment. (address, dob, salutation)
> [change] (UMCS-245) Payment Page examples: 

- CHANGELOG.md
- composer.json
- src/Resources/Config.php
- src/Resources/Recurring.php
- src/Resources/TransactionTypes/Shipment.php
- src/Resources/Webhook.php
- src/Services/HttpService.php
- src/Services/IdService.php
- src/Unzer.php
- src/Validators/PrivateKeyValidator.php
- src/Validators/PublicKeyValidator.php
- test/integration/ConfigTest.php
- Enable PHP 8.1 as composer dependency.
- Fix parameter type incompatibility issues with PHP 8.1.
- Minor code style changes
> UMCS-303: PHP 8.1 compatibility

- CHANGELOG.md
- src/Constants/ApiResponseCodes.php
- src/Interfaces/ResourceServiceInterface.php
- src/Resources/AbstractUnzerResource.php
- src/Resources/Basket.php
- src/Resources/EmbeddedResources/BasketItem.php
- src/Services/HttpService.php
- src/Services/ResourceService.php
- src/Unzer.php
- test/BasePaymentTest.php
- test/integration/BasketTest.php
- test/integration/BasketV2Test.php
- test/unit/Resources/AbstractUnzerResourceTest.php
- test/unit/Resources/BasketTest.php
- test/unit/Resources/EmbeddedResources/BasketItemTest.php
- test/unit/Services/ResourceServiceTest.php
- Update basket resource to support v2/basket.
> Umcs 419/update basket

- CHANGELOG.md
- src/Constants/ShippingTypes.php
- src/Resources/Customer.php
- src/Resources/EmbeddedResources/Address.php
- src/Resources/EmbeddedResources/CompanyInfo.php
- src/Resources/EmbeddedResources/CompanyOwner.php
- test/Fixtures/CustomerFixtureTrait.php
- test/integration/CustomerTest.php
- test/unit/Resources/CustomerTest.php
- test/unit/Resources/EmbeddedResources/CompanyOwnerTest.php
- Add companyInfo.owner property.
- Add companyInfo.companyType property.
- Add shippingType to `Address` usable for any kind of address.
> Umcs 453/upl extend customer data

- CHANGELOG.md
- examples/CardRecurring/RecurringPaymentController.php
- examples/ChargePaymentController.php
- examples/Constants.php
- examples/PaylaterInvoice/Constants.php
- examples/PaylaterInvoice/Controller.php
- examples/PaylaterInvoice/index.php
- examples/Success.php
- examples/index.php
- Add Paylater Invoice example.
- Display of payment data is disabled for the moment, since an update of authorization transaction is required and will be provided in a separate PR.
> Umcs 478/add upl example

- src/Interfaces/PaymentServiceInterface.php
- src/Services/PaymentService.php
- src/Unzer.php
- test/Fixtures/CustomerFixtureTrait.php
- test/integration/PaymentTypes/InvoiceGuaranteedTest.php
- test/integration/PaymentTypes/PaylaterInvoiceTest.php
- smaller adjustments found during qa.
> Umcs 383/qa changes

- CHANGELOG.md
- src/Interfaces/PaymentServiceInterface.php
- Add deprecation notes to changelog.
- Also mark `chargePayment` and `chargeAuthorization` as deprecated
> UMCS-383(change) Add deprecation notes to changelog.

- CHANGELOG.md
- src/Interfaces/ResourceServiceInterface.php
- src/Resources/Config.php
- src/Resources/InstalmentPlans.php
- src/Services/ResourceService.php
- src/Unzer.php
- test/integration/ConfigTest.php
- test/unit/Resources/ConfigTest.php
- Add function to fetch payment type config from Payment API
- Reformated changelog
> Umcs 383/paylater invoice config

- CHANGELOG.md
- examples/Alipay/index.php
- examples/Bancontact/index.php
- examples/BankTransfer/index.php
- examples/Card/index.php
- examples/CardExtended/index.php
- examples/CardRecurring/index.php
- examples/EPSCharge/index.php
- examples/EmbeddedPayPage/index.php
- examples/Giropay/index.php
- examples/HostedPayPage/index.php
- examples/IDeal/index.php
- examples/InstallmentSecured/index.php
- examples/Invoice/index.php
- examples/InvoiceSecured/index.php
- examples/Klarna/index.php
- examples/PayPal/index.php
- examples/PayPalRecurring/index.php
- examples/PaylaterInvoice/index.php
- examples/Prepayment/index.php
- examples/Przelewy24/index.php
- examples/SepaDirectDebitSecured/index.php
- examples/Sofort/index.php
- examples/Wechatpay/index.php
- Place all pay-buttons into a div with "field" class.
- ensure that all payment forms use correct css classes.
- Examples: Disable pay-button by default for examples that have mandatory input fields.
> Umcs 518/adjust example form classes

- examples/Backend/Failure.php
- examples/EmbeddedPayPage/Controller.php
- examples/HostedPayPage/Controller.php
- examples/index.php
- fix "start again" link.
- Add language to customer for payment pages.
- Removed incorrect description.
> (UMCS-563) adjust examples based on qa findings:

- CHANGELOG.md
- src/Resources/TransactionTypes/Charge.php
- src/Services/CancelService.php
- test/unit/Services/CancelServiceTest.php
> Umcs 563/separate prd sbx environments

- test/integration/PaymentTypes/ApplepayTest.php
- test/integration/TransactionTypes/ChargeTest.php
- Deactivate applepay tests for the time being.
- Fix chargetest.
> (UMCS-631) Adjust automatic tests:

- CHANGELOG.md
- examples/Constants.php
- examples/Create.php
- examples/ReturnController.php
- test/integration/PaymentTypes/PaypageTest.php
- Also updated changelog regarding php support due to  #130
> Umcs 440/examples handle create state

- CHANGELOG.md
- src/Unzer.php
Version update for upcoming release.
> Release 3.1.0

- src/Constants/IdStrings.php
- src/Resources/AbstractUnzerResource.php
- src/Resources/PaymentTypes/PayU.php
- src/Services/HttpService.php
- src/Services/ResourceService.php
- src/Services/ValueService.php
- src/Traits/CanAuthorizeWithCustomer.php
- src/Traits/CanDirectCharge.php
- test/integration/BasketTest.php
- test/integration/BasketV2Test.php
- test/integration/PaymentTypes/CardTest.php
- test/integration/PaymentTypes/PayUTest.php
- test/integration/WebhookTest.php
- test/unit/Resources/BasketTest.php
- test/unit/Services/HttpServiceTest.php
Changelog entry already added in #153
> Cc 510/payu

- CHANGELOG.md
- README.md
- src/Constants/IdStrings.php
- src/Resources/PaymentTypes/PaylaterDirectDebit.php
- src/Resources/PaymentTypes/Paypage.php
- src/Resources/PaymentTypes/SepaDirectDebit.php
- src/Resources/PaymentTypes/SepaDirectDebitSecured.php
- src/Services/ResourceService.php
- test/integration/PaymentTypes/HirePurchaseTest.php
- test/integration/PaymentTypes/InstallmentSecuredTest.php
- test/integration/PaymentTypes/PaylaterDirectDebitTest.php
- test/integration/PaymentTypes/PaypalTest.php
- test/integration/PaymentTypes/Przelewy24Test.php
- test/unit/Resources/EmbeddedResources/RiskDataTest.php
- test/unit/Resources/EmbeddedResources/ShippingDataTest.php
- test/unit/Resources/PaymentTypes/PayPageTest.php
- test/unit/Resources/PaymentTypes/PaylaterDirectDebitTest.php
- test/unit/Resources/PaymentTypes/SepaDirectDebitTest.php
- test/unit/Resources/TransactionTypes/ChargeTest.php
- test/unit/UnzerTest.php
- Also added unit test for for CC-586
- includes CC-574
> Cc 570/paylater direct debit

- examples/EmbeddedPayPage/Controller.php
- examples/HostedPayPage/Controller.php
- examples/PaylaterInvoice/Controller.php
- examples/index.php
Release-PHP-SDK-3] Add missing use statement for unzer invoice example.
> [CC-584 Release-PHP-SDK-3] qa

- .github/workflows/unit-tests.yml
- composer.json
- Add version constraint to composer.json
- Add version to unit test workflow.
> [CC-741] Add php 8.3 version

- test/integration/Resources/PaypageV2Test.php
> [CC-1337] Add Paypage V2:

- CHANGELOG.md
- src/Unzer.php
- Update SDK version.
- Update changelog.
- Minor phpdoc changes.
> [CC-1474] Release 3.8.0:

- .gitignore
- src/Resources/EmbeddedResources/Paypage/AmountSettings.php
- src/Resources/EmbeddedResources/Paypage/PaymentMethodsConfigs.php
- src/Resources/EmbeddedResources/Paypage/Style.php
- src/Resources/V2/Paypage.php
- src/Services/ResourceService.php
- src/Unzer.php
- test/integration/Resources/LinkpayV2Test.php
- test/integration/Resources/PaypageV2Test.php
Covers:
- CC-1581
- CC-1646
- CC-1583
> CC-1581/add-linkpay-creation
